---
title: 'Kausaliteten mellem landbrugets udvikling med fokus på svin og jernbanens
  udbredelse i Danmark'
author: "Regitze Steensgaard"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M:%S')`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false 
      smooth_scroll: false
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE,
                      message = TRUE)
```


```{r, eval= FALSE, include=FALSE}
# Jeg laver genveje til mit data og figurer.
dir.create("data")
dir.create("data_output")
dir.create("fig_output")



```


```{r indhenter_data, include=FALSE}

# jeg installere de pakker, som skal bruges.
library(tidyverse)
library(here)
library(scales)

# Jeg henter mit ene datasæt ind i R, som er en csv fil. 
# Jeg anvender tidyverse pakken. Derfor skal der anvendes "_" ved read_csv2. 

data_svin_i_dk_og_jernbaner <- read_csv2("data/data_svin_i_dk_jernbaner.csv")


```


```{r ny_kolonne_1, include=FALSE}

# Jeg opretter en ny kolonne gennem "mutate". I den kolonne skal værdierne fra xx antal kolonner indgå. Det, som udregnes, er antallet af svin i alt for Danmark.
# rowsums er en funktion til at beregne den totale sum af kolonnerne. select udvælger kolonnerne. 
data_svin_i_dk_og_jernbaner <- data_svin_i_dk_og_jernbaner %>%
  mutate(svin_i_alt = rowSums(select(., kbh_stad, kbh_amt, frederiksborg_amt, holbaek_amt, sorae_amt,praesteoe_amt,bornholms_amt,odense_amt, svendborg_amt, maribo_amt, aalborg_amt, hjoerring_amt, thisted_amt, viborg_amt, aarhus_amt, randers_amt, ribe_amt, ringkoebing_amt, vejle_amt)))
```

```{r ny_kolonne_2, include=FALSE}
# Jeg opretter endnu en ny kolonne gennem "mutate" funktionen. Jeg udregner total antal svin for Jylland-Fyn.
data_svin_i_dk_og_jernbaner <- data_svin_i_dk_og_jernbaner %>% 
  mutate(total_svin_jylland_fyn= odense_amt+svendborg_amt+aalborg_amt+hjoerring_amt+thisted_amt+viborg_amt+aarhus_amt+randers_amt+ribe_amt+ringkoebing_amt+vejle_amt)

```


```{r ny_kolonne_3, include=FALSE}
# Jeg opretter endnu en ny kolonne gennem "mutate" funktionen. Jeg udregner total antal svin for Sjælland-Øerne.
data_svin_i_dk_og_jernbaner <- data_svin_i_dk_og_jernbaner %>% 
  mutate(total_svin_sjaelland_oeerne= kbh_stad+kbh_amt+frederiksborg_amt+holbaek_amt+sorae_amt+praesteoe_amt+bornholms_amt+maribo_amt)


```

## Graf over total antal svin


```{r total_svin, eval=TRUE}
# Jeg laver en graf over antal af svin total. Derfor udvælges hvilket datasæt, som dataet skal findes i og fra hvilken kolonne.
# Med !is.na filtres alle NA væk.
# Geomline er typen af graf, her et linjediagram.
# Med scales kan jeg justere grafens udseende, fx antallet af år, som x-aksen skal springe imellem.
# Med lab navngives graftens værdier 
udvikling_i_antal_svin_total <- data_svin_i_dk_og_jernbaner %>%
  filter(!is.na(svin_i_alt)) %>%
  ggplot(aes(x = aar, y = svin_i_alt, colour = svin_i_alt)) +
  geom_line() +
  scale_y_continuous(labels = label_number(big.mark = ".", decimal.mark = ",")) +
  scale_x_continuous(breaks = seq(1837, 1914, by = 5)) +
  xlab("År") +
  ylab("Antal svin") +
  labs(title = "Udvikling i antallet af svin", colour = "Antal Svin") +
  theme_bw()

# grafen gemmes i fig_output
ggsave(plot = udvikling_i_antal_svin_total, 
       here("fig_output","udvikling_i_antal_svin_total.png"), 
       height = 6, 
       width = 10)

# Visning af grafen
udvikling_i_antal_svin_total


```
## Graf over antal svin

```{r svin_total_og_landområder, eval=TRUE}
# Jeg laver en graf over antal af svin total og af antal svin pr. område ved Jylland-Fyn og Sjælland-Øerne. Derfor udvælges hvilket datasæt, som dataet skal findes i og fra hvilke kolonner.
# Med !is.na filtres alle NA væk.
# Geomline er typen af graf, her et linjediagram.
# Med scales kan jeg justere grafens udseende, fx antallet af år, som x-aksen skal springe imellem. Men også hvordan y-værdien skal vises. Her bruges fx "." i værdien.
# Med lab navngives graftens værdier
udvikling_i_svin_pr_område_total <- data_svin_i_dk_og_jernbaner %>%
  filter(!is.na(svin_i_alt)) %>%
  ggplot(aes(x = aar)) +
  geom_line(aes(y = total_svin_jylland_fyn, color = "Jylland_Fyn")) +
  geom_line(aes(y = total_svin_sjaelland_oeerne, color = "Sjælland_Øerne")) +
  geom_line(aes(y = svin_i_alt, color = "Svin total")) +
  scale_x_continuous(breaks = seq(1837, 1914, by = 5))+
  xlab("År")+
  ylab("Antal svin")+
  scale_y_continuous(labels = label_number(big.mark = ".", decimal.mark = ","))+
  labs(color = "Område", title = "Antal svin fordelt på landområder")+
  theme_bw()

# Gemmer grafen
ggsave(plot = udvikling_i_svin_pr_område_total, 
       here("fig_output","udvikling_i_svin_pr_område_total.png"), 
       height = 6, 
       width = 10)

# Visning af grafen 
udvikling_i_svin_pr_område_total

```

```{r indhenter_data1, include=FALSE}
# Mit andet datasæt hentes ind i R, og jeg anvender igen tidyverse, derfor bruges "_" ved read_csv2.
data_eks_flaesk <- read_csv2("data/eksport_af_flaesk.csv")
```
## Graf over eksport af flæsk 

```{r eskport_flaesk, eval=TRUE}
# Der laves en graf over total mængde flæsk eksporteret fra Danmark til forskellige lande.
# Jeg anvender facet-wrap, som opdeler dataet i flere paneler, ud fra den valgte kolone, som dataet skal opdeles i: ~land 
# Med !is.na filtres alle NA væk.
# Geomline er typen af graf, her et linjediagram.
# Med scales kan jeg justere grafens udseende, fx antallet af år, som x-aksen skal springe imellem. Men også hvordan y-værdien skal vises. Her bruges fx "." i værdien.
# Med lab navngives graftens værdier
eksport_af_flaesk_pr_område <- data_eks_flaesk %>% 
  filter(!is.na(eks_flaesk), 
         land == "tyskland" | land == "sverige" | land == "norge" | land == "andre_lande") %>%
  ggplot(aes(x = aar, y = eks_flaesk, color = land)) +
  geom_line() +
  facet_wrap(~land) + 
  scale_x_continuous(breaks = seq(1864, 1894, by = 4)) +
  scale_y_continuous(labels = label_number(big.mark = ".", decimal.mark = ",")) +
  xlab("År")+
  ylab("Eksport af flæsk i pund")+
  labs(title = "Eksport af flæsk", color= "Lande") +
  theme_bw()

# Grafen gemmes
ggsave(plot = eksport_af_flaesk_pr_område, 
       here("fig_output","eksport_af_flaesk_pr_område.png"), 
       height = 6, 
       width = 10)

# Grafen vises
eksport_af_flaesk_pr_område

```

## Graf over eskport af flæsk med England

```{r eksport_flaesk_med_england, eval=TRUE}
# Jeg laver en graf over total mængde eksport af flæsk fra Danmark, hvor England også er inddraget. Derfor udvælges hvilket datasæt, som dataet skal findes i og fra hvilke kolonner.
# Med !is.na filtres alle NA væk.
# Geomline er typen af graf, her et linjediagram.
# Med scales kan jeg justere grafens udseende, fx antallet af år, som x-aksen skal springe imellem. Men også hvordan y-værdien skal vises. Her bruges fx "." i værdien.
# Med lab navngives graftens værdier.
total_oversigt_af_eks_flaesk <- data_eks_flaesk %>% 
  filter(!is.na(eks_flaesk)) %>%
  ggplot(aes(x = aar, y = eks_flaesk, color = land)) +
  geom_line() +
  scale_x_continuous(breaks = seq(1864, 1894, by = 4)) +
  scale_y_continuous(labels = label_number(big.mark = ".", decimal.mark = ",")) +
  xlab("År")+
  ylab("Eksport af flæsk i pund")+
  labs(title = "Samlet oversigt over eksport af flæsk", color= "Lande") +
  theme_bw()

# Grafen gemmes
ggsave(plot = total_oversigt_af_eks_flaesk, 
       here("fig_output","total_oversigt_af_eks_flaesk.png"), 
       height = 6, 
       width = 10)

# Grafen vises
total_oversigt_af_eks_flaesk

```

## Graf over eksport af flæsk sammenlignet med England

```{r total_eksport_flaesk_med_england, eval=TRUE}
# Der laves en graf over den totale mængde eksport af flæsk sammenlignet med England.
# Med !is.na filtres alle NA væk.
# Geomline er typen af graf, her et linjediagram.
# Med scales kan jeg justere grafens udseende, fx antallet af år, som x-aksen skal springe imellem. Men også hvordan y-værdien skal vises. Her bruges fx "." i værdien.
# Med lab navngives graftens værdier.
total_eksport_og_england <- data_svin_i_dk_og_jernbaner %>% 
  filter(!is.na(eks_flaesk_england),
         !is.na(total_eks_flaesk)) %>%
  ggplot(aes(x = aar)) +
  geom_line(aes(y = total_eks_flaesk, color = "Total eksport")) +
  geom_line(aes(y = eks_flaesk_england, color = "Eksport til England")) +
  scale_x_continuous(breaks = seq(1864, 1894, by = 4)) +
  scale_y_continuous(labels = label_number(big.mark = ".", decimal.mark = ",")) +
  xlab("År")+
  ylab("Eskport af flæsk i pund")+
  labs(title = "Total eksport af flæsk sammenlignet med England", color = "Fordeling") +
  theme_bw()

# Grafen gemmes
ggsave(plot = total_eksport_og_england, 
       here("fig_output","total_eksport_og_england.png"), 
       height = 6, 
       width = 10)

# Grafen vises
total_eksport_og_england

```

```{r ny_kolonne_4, include=FALSE}
# Der udregnes den totale længde af jernbanen i hele Danmark og ikke kun for Jylland-Fyn og Sjælland-Øerne. Derfor laves en ny kolonne med mutate, hvor værdien indgår.
data_svin_i_dk_og_jernbaner <- data_svin_i_dk_og_jernbaner %>% 
  mutate(total_laengde_jernbane= jysk_fynsk_jernbane+sjaelland_oeerne_jernbane)
```

## Graf over jernbanens længde

```{r total_laengde_jernbane_og_landområder, eval=TRUE}
# Der laves en graf over jernbanens totale længde og Jylland-Fyn og Sjælland-Øernes 
# Med !is.na filtres alle NA væk.
# Geomline er typen af graf, her et linjediagram.
# Med scales kan jeg justere grafens udseende, fx antallet af år, som x-aksen skal springe imellem. 
# Med lab navngives graftens værdier.
udvikling_af_jernbanens_laengde <- data_svin_i_dk_og_jernbaner %>%
  filter(!is.na(jysk_fynsk_jernbane),
         !is.na(sjaelland_oeerne_jernbane),
         !is.na(total_laengde_jernbane)) %>%  
  ggplot(aes(x = aar)) +
  geom_line(aes(y = jysk_fynsk_jernbane, color = "Jylland_Fyn jernbane")) +
  geom_line(aes(y = sjaelland_oeerne_jernbane, color = "Sjælland_Øerne jernbane")) +
  geom_line(aes(y = total_laengde_jernbane, color = "Total længde af jernbane")) +
  xlab("År")+
  ylab("Jernbanenes længde i kilometer")+
  labs(title = "Jernbanes længde i Danmark", color = "Område") +
  scale_x_continuous(limits = c(1866, 1914), breaks = seq(1866, 1914, by = 4)) +
  theme_bw()

# Grafen gemmes 
ggsave(plot = udvikling_af_jernbanens_laengde, 
       here("fig_output","udvikling_af_jernbanens_laengde.png"), 
       height = 6, 
       width = 10)

# Grafen vises
udvikling_af_jernbanens_laengde


```

```{r kilometer_oegning, include=FALSE}
# Der udregnes hvor meget jernbanens længde er vokset med i den udvalgte periode.
# Det udregnes mellem den største og mindste værdi valgt fra kolonen total_laengde_jernbane med $
# NA ignores her med na.rm=TRUE
kilometer_øgning <- max(data_svin_i_dk_og_jernbaner$total_laengde_jernbane, na.rm = TRUE)-min(data_svin_i_dk_og_jernbaner$total_laengde_jernbane, na.rm= TRUE)

# Viser resultatet
print(kilometer_øgning)

```


